database:
  db_type: postgres
  mysql:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: 
    dbname: mydb
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    user: root
    password: secret
    dbname: mydb
  redis:
    default:
      driver: redis
      host: localhost
      port: 6379
      password: postgres
      dbname: 0
    cache:
      driver: redis
      host: localhost
      port: 6379
      password: postgres
      dbname: 1

server:
  port: 8000
template_engine: pongo2
template_dir: "./resources"
smtp:
  host: smtp.gmail.com
  port: 587
  username: your_username@gmail.com
  password: your_password
  encryption: tls
  mailer: smtp
logging:
  path: "./storage/logs/logs.txt"
cookie:
  name: "my_cookie"
  path: "/"
  domain: "example.com"
  expires: "2030-12-31T00:00:00Z"
  secure: true
  samesite: strict
  httponly: true
session:
  type: "file"
  key: "my-secret-key"
  expirationTime: "2h"
  file: 
    path: "./storage/sessions/logs.txt"
cache:
  type: memory
  file: 
    path: "./storage/cache/logs.txt"
storage:
  default: local
  disks:
    local:
      driver: local
      base_path: "./storage"
    s3:
      driver: s3
      bucket: "your-s3-bucket"
