database:
  db_type: mysql
  mysql:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: secret
    dbname: mydb
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    dbname: mydb
server:
  port: 8000
template_engine: pongo2
template_dir: "./resources"
smtp:
  host: smtp.gmail.com
  port: 587
  username: your_username@gmail.com
  password: your_password
logging:
  path: "./storage/logs/logs.txt"
cookie:
  name: "my_cookie"
  path: "/"
  domain: "example.com"
  expires: "2030-12-31T00:00:00Z"
  secure: true
  samesite: strict
  httponly: true
session:
  type: "file"
  key: "my-secret-key"
  expirationTime: "2h"
  file: 
    path: "./storage/sessions/logs.txt"
 