database:
  db_type: mysql
  mysql:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: secret
    dbname: mydb
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    dbname: mydb
server:
  port: 8000
template_engine: pongo2

